### ISSUE TITLE
Unable to complete installation: cyuser@localhost: Permission denied (publickey).

### ISSUE THREAD

**Issue by TimDiam0nd** [crond-jaist/cyris#10]
I am currently installing cyris on ubuntu 18.04. The host has been prepared according to the documentation, however after following the instructions on the linked digitalocean article, I keep getting the following error: 

```
cyuser@localhost: Permission denied (publickey).
```

Running the parallel-ssh command seperately with the -A option gives the following output:

```
parallel-ssh -A -v -O StrictHostKeyChecking=no -O UserKnownHostsFile=/dev/null -i -h /home/cyuser/cyris/settings/123pssh_host.txt -t 300 -p 50 -x '-tt' "mkdir -p
home/cyuser/cyris/cyber_range/123/; mkdir /home/cyuser/cyris/cyber_range/123/images;"
Warning: do not enter your password if anyone else has superuser
privileges or access to your account.
Password:
[1] 22:20:57 FAILURE cyuser@localhost:22 Exited with error code 255
Warning: Permanently added 'localhost' (ECDSA) to the list of known hosts.
cyuser@localhost: Permission denied (publickey).
```

I have also edited /etc/ssh/sshd-config to allow passwordless authentication, root and a few other things.

Are there any particular things I need to edit in my sshd-config or any other steps I should take, since I cant seem to figure it out?

Thanks

**Comment by crond-jaist** [comment]
Hi,

Based on the error you mention, I don't think that your problem is related to CyRIS itself, but to the fact that public key authentication was not set up correctly. If it works, you should be able to login via the command `ssh cyuser@localhost` without typing your password. If this fails, you need to set up again public key authentication. 

While I don't know about your particular case, many times permissions for the `.ssh` directory or the `authorized_keys` files can be the reason for the error you see. I hope this helps.

Best wishes,
Razvan
