### ISSUE TITLE
Clone VM check ssh connectivity failure

### ISSUE THREAD

**Issue by kbsenthilkumar** [crond-jaist/cyris#5]
SSH connectivity check to the clone VM results in failure.  I have pasted below content of creation.log and last few lines of terminal output.  Please advice.

=====================================================
                                       CREATION.LOG
========================================================
_Domain desktop_cr123_base started
/root/cyris-1.1/instantiation/sshkey_hostname_setup/sshkey_setup.sh 192.168.122.102 theroot root; /root/cyris-1.1/instantiation/sshkey_hostname_setup/hostname_setup.sh 192.168.122.102 theroot desktop;Warning: Permanently added '192.168.122.102' (ECDSA) to the list of known hosts.
[1] 16:56:50 [SUCCESS] root@10.176.26.151:22
interface eth123-1-1 does not exist!

Waiting for br123-1-1 to get ready (MAXWAIT is 2 seconds).
RTNETLINK answers: File exists
Failed to bring up br123-1-1.
 bridges are up

* Enter VM cloning script 'vm_clone_xml.sh'
** Create disk image 'desktop_cr123_1_1_img' for the cloned VM
Formatting '/root/cyris-1.1/cyber_range/123/images/desktop_cr123_1_1_img', fmt=qcow2 size=21474836480 backing_file=/root/cyris-1.1/cyber_range/123/desktop encryption=off cluster_size=65536 lazy_refcounts=off refcount_bits=16
** Create XML config file 'desktop_cr123_1_1_config.xml' for the cloned VM
** Define the cloned VM using config file 'desktop_cr123_1_1_config.xml'
Domain desktop_cr123_1_1 defined from /root/cyris-1.1/cyber_range/123/images/desktop_cr123_1_1_config.xml

** Start the cloned VM 'desktop_cr123_1_1'
Domain desktop_cr123_1_1 started

* Exit VM cloning script 'vm_clone_xml.sh'

Warning: Permanently added 'localhost' (ECDSA) to the list of known hosts.

Stderr: Warning: Permanently added '10.176.26.151' (ECDSA) to the list of known hosts.
Connection to 10.176.26.151 closed._

==============================================================
                               TERMINAL OUTPUT
================================================================

* DEBUG: cyris:       Check SSH connectivity to 123.1.1.2 => FAILURE
Warning: Permanently added '10.176.26.151' (ECDSA) to the list of known hosts.
Warning: Permanently added '123.1.1.2' (ECDSA) to the list of known hosts.

* DEBUG: cyris:       Check SSH connectivity to 123.1.1.2 => FAILURE
* ERROR: cyris: Cannot connect to VM.
  Error on connect: Warning: Permanently added '10.176.26.151' (ECDSA) to the list of known hosts.
Warning: Permanently added '123.1.1.2' (ECDSA) to the list of known hosts.

  Check the log file for details: /root/cyris-1.1/cyber_range/123/creation.log
-------------------------------------------------------------------------
* INFO: cyris: Cyber range creation status: FAILURE
  Check the log file for details: /root/cyris-1.1/cyber_range/123/creation.log
-------------------------------------------------------------------------

**Comment by crond-jaist** [comment]
Please provide some more information about this issue:
* Did CyRIS work correctly before? If yes, did you change anything between now and then?
* Is the cloned VM desktop_cr123_1_1 actually created by KVM? You can check this by using "virsh list --all".
* What OS are you using?

**Comment by kbsenthilkumar** [comment]
I have given my answers inline below.

  *   Did CyRIS work correctly before? If yes, did you change anything between now and then?
     *   No. This is the first time.
  *   Is the cloned VM desktop_cr123_1_1 actually created by KVM? You can check this by using "virsh list --all".
     *   Yes, it is created by KVM​
  *   What OS are you using?
     *   Ubuntu 16.04 LTS

If we comment the sshkey_setup.sh, then it succeeds. Then cyris fails while setting the default gateway.

I have attached the complete terminal output for your reference.


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by crond-jaist** [comment]
I have looked at the log, and it seems that there is a network problem, as the VM is not accessible (hence the "No route to host" error). I suggest that you try to run the same command as CyRIS:

ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o PasswordAuthentication=no -o ConnectTimeout=5 123.1.1.2 ls

and see if you can make it work by changing some settings yourself. I suspect the bridge may not be correctly set up, so you should check whether the bridge created by CyRIS with address "123.1.1.1" is operational. 

Moreover, each time you have a failure, make sure you cleanup the cyber range files, for instance via "range_cleanup.py", otherwise conflicts can occur.

**Comment by kbsenthilkumar** [comment]
Thanks for the reply.

"No route to host" error is because of VM booting up. However the issue here is after the VM boots up, SSH check to it fails with the error message given below.  Please refer line number 122-1233 in the attachement.

  ERROR ON CONNECT: WARNING: PERMANENTLY ADDED '10.176.26.151' (ECDSA) TO THE LIST OF KNOWN HOSTS.
WARNING: PERMANENTLY ADDED '123.1.1.2' (ECDSA) TO THE LIST OF KNOWN HOSTS.


I think the SSH connectivity check should return "Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password)."

Please advise. I have attached creation.log for your reference.


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by crond-jaist** [comment]
First of all, I could not find any attachment to your message.

Secondly, we did not encounter anything similar to the error you mention, and I suspect it could be caused by some wrong configuration of your system. In the previous message I asked you to check manually whether you can indeed connect to the cloned VM 123.1.1.2, but you didn't reply about it. Did you try?

In any case, I suggest that you clean all the network settings of your host, including bridges, and also shutdown running VMs, etc. so that you can start fresh. Redownloading the base VM image is also advised if you made any changes to it.

I am afraid that we cannot help you much for this case, and if the error still occurs after you freshen up your system, you will have to investigate deeper by yourself to understand the actual cause.

**Comment by crond-jaist** [comment]
Closed because of lack of feedback from the person who opened the issue.
